// <auto-generated />
using System;
using Hospital.HospitalData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240419145339_1231")]
    partial class _1231
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "noooo"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Bones and Joints"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Women's Health"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "General physician"
                        });
                });

            modelBuilder.Entity("Hospital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Fees")
                        .HasColumnType("float");

                    b.Property<string>("Hospital")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Specialisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Docinfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fees = 500.0,
                            Hospital = "Appolo",
                            Name = "test1",
                            Specialisation = "neuro"
                        },
                        new
                        {
                            Id = 2,
                            Fees = 1000.0,
                            Hospital = "United",
                            Name = "test2",
                            Specialisation = "ortho"
                        },
                        new
                        {
                            Id = 3,
                            Fees = 700.0,
                            Hospital = "Narayana",
                            Name = "test3",
                            Specialisation = "surgeon"
                        });
                });

            modelBuilder.Entity("Hospital.Models.Hospitals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitalinfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Appolo",
                            Description = "neuro",
                            ImageUrl = "",
                            Name = "test1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "United",
                            Description = "ortho",
                            ImageUrl = "",
                            Name = "test2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Narayana",
                            Description = "surgeon",
                            ImageUrl = "",
                            Name = "test3"
                        });
                });

            modelBuilder.Entity("Hospital.Models.Patients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Record")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PatientsList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            BloodGroup = "O+",
                            City = "Nyc",
                            Name = "xyz",
                            PhoneNumber = "9876567657",
                            Problem = "Throat",
                            Record = ""
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            BloodGroup = "ab+",
                            City = "Del",
                            Name = "xyz1",
                            PhoneNumber = "9876567657",
                            Problem = "skin",
                            Record = ""
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            BloodGroup = "b+",
                            City = "Blr",
                            Name = "xyz2",
                            PhoneNumber = "9876567657",
                            Problem = "hair",
                            Record = ""
                        },
                        new
                        {
                            Id = 4,
                            Age = 24,
                            BloodGroup = "a+",
                            City = "Hyd",
                            Name = "xyz3",
                            PhoneNumber = "9876567657",
                            Problem = "joint",
                            Record = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
